branch-defaults:
  master:
    environment: trydjango19-dev
    group_suffix: null
global:
  application_name: trydjango19
  default_ec2_keyname: Sangheun-key-pair-Seoul
  default_platform: Python 3.4
  default_region: ap-northeast-2
  profile: eb-cli
  sc: git
